### PR TITLE
Allow create notice settings for any model

### PR DESCRIPTION
**Pull request by purple-sunrise**
This fix allow to send notifications to people in any tables/models (in my case there are two tables: user and person). I don't want to create user account for any person, but I want send notifications to them.

### CODE REVIEW

**Comment by paltman** [comment]
1. Notice settings are very much a user centric thing
2. The latest thing pushed to this repo was support of extending the NoticeSetting model to add other attributes to scope the notifications. 
3. Your local copy is out of date (as indicated by the greyed out merge button)

**Comment by paltman** [comment]
What is the use case you are trying to support?

**Comment by purple-sunrise** [comment]
I have system with users and persons. Persons have emails. And I want to send notifications on this emails sometimes. But I don't want to create user instance for this persons.

**Comment by paltman** [comment]
Are Person and User related?

**Comment by purple-sunrise** [comment]
No.

**Comment by paltman** [comment]
Then I think pinax-notifications is the wrong app for what you want. One of the core features is for users to be able to control what and how they receive notifications that the system sends out.

**Comment by purple-sunrise** [comment]
If I send notification to person, it can't create NoticeSettings for Person's instance. But in case of using generic relations it works. Yes, this add some difficulty in admin interface, but also add flexibility.

**Comment by paltman** [comment]
If you want to fork pinax-notifications and go a different direction with it, you have my complete support and encouragement.

At this time, we will not be adding GFK support instead of a direct link to user instance.

**Pull request closed without merging**
